### ISSUE TITLE
Timer should be reset when the user manually changes the banner

### ISSUE THREAD

**Issue by lbebber** [vtex-apps/carousel#39]
Right now there seems to be a fixed timer that switches the current banner every X seconds. 

When the user clicks on, say, "next", right before the time is up, the banner is skipped right away.

Or something like that, the behaviour seems to be kind of uneven. But just play around with the banner and you will see that happening.

When the user clicks "next" or "prev" or drags the banner, the auto-switch interval should be reset (and perhaps even extended, because if the user has manually selected a banner, they are probably interested in it for some reason)

**Comment by Klynger** [comment]
I see that this is an old issue, but this problem still exists in the new implementation of the [Slider](https://github.com/vtex-apps/slider), if you pass `autoplay={true}` and `pauseOnHover={false}` this problem will happen, this is not going to happen here in the `Carousel` since `pauseOnHover` is always true. Gonna fix this when I fix other bugs that are happening :smile:
